export const STOCK_RESEARCH_FIXTURE = {
  NVDA: {
    id: 'stock-nvda',
    symbol: 'NVDA',
    company_name: 'NVIDIA',
    status: '후보',
    primary_reason: '추세 유지 + 성장성 + 포트 적합도 우수',
    is_held: false,
    hold_action: null,
    display_judgment: '매수 후보',
    score_drivers: ['성장 모멘텀', '섹터 중복'],
    risk_flags: ['반도체 섹터 중복 높음'],
    sector_overlap_flags: ['반도체 중복 높음'],
    scoring_breakdown: { stock_quality_raw: 88, portfolio_fit_raw: 82, concentration_penalty: 9 },
    chart_series: [{ date: '2026-03-10', close: 118 }, { date: '2026-03-11', close: 121 }],
    chart_markers: [{ kind: 'earnings', date: '2026-03-15', label: '실적' }],
    price_zones: [{ label: '지지', value: 112 }],
    chart_notes: ['20일선 위', '실적 전 변동성 확대'],
    macro_summary: '금리 안정과 성장주 선호가 이어지는 구간입니다.',
    options_summary: '실적 전 IV 상승이 관찰됩니다.',
    memo: 'AI 인프라 핵심 수혜 여부 추적',
    next_action: '실적 발표 후 가이던스 확인',
    captures: [{ id: 'nvda-chart', label: '차트 캡처', image_url: '/vite.svg' }],
    overlap_details: [{ type: 'sector', label: '반도체', impact: 'high', reason: 'AI 반도체 노출이 이미 높습니다.' }],
  },
  AMZN: {
    id: 'stock-amzn',
    symbol: 'AMZN',
    company_name: 'Amazon',
    status: '관찰',
    primary_reason: '중복은 낮지만 아직 확신은 부족',
    is_held: false,
    hold_action: null,
    display_judgment: '매수 후보',
    score_drivers: ['중복 낮음'],
    risk_flags: [],
    sector_overlap_flags: [],
    scoring_breakdown: { stock_quality_raw: 68, portfolio_fit_raw: 74, concentration_penalty: 2 },
    chart_series: [{ date: '2026-03-10', close: 201 }, { date: '2026-03-11', close: 204 }],
    chart_markers: [],
    price_zones: [{ label: '저항', value: 210 }],
    chart_notes: ['박스권 상단 접근'],
    macro_summary: '소비 둔화 우려와 클라우드 방어력이 혼재합니다.',
    options_summary: '옵션시장 이벤트 프리미엄은 제한적입니다.',
    memo: '클라우드 성장률 재확인 필요',
    next_action: '다음 실적 전 체크포인트 정리',
    captures: [],
    overlap_details: [],
  },
  AAPL: {
    id: 'stock-aapl',
    symbol: 'AAPL',
    company_name: 'Apple',
    status: '관찰',
    primary_reason: '품질은 괜찮지만 보유 비중과 집중도가 부담',
    is_held: true,
    hold_action: '축소 검토',
    display_judgment: '축소 검토',
    score_drivers: ['보유중', '테마 중복'],
    risk_flags: ['대형 기술주 편중'],
    sector_overlap_flags: ['대형 기술주 편중'],
    scoring_breakdown: { stock_quality_raw: 72, portfolio_fit_raw: 41, concentration_penalty: 12 },
    chart_series: [{ date: '2026-03-10', close: 188 }, { date: '2026-03-11', close: 186 }],
    chart_markers: [{ kind: 'risk', date: '2026-03-11', label: '비중 경고' }],
    price_zones: [{ label: '리스크', value: 185 }],
    chart_notes: ['상단 탄력 둔화'],
    macro_summary: '시장 우호에도 개별 비중 부담이 큽니다.',
    options_summary: '업사이드 기대보다 방어적 포지션이 많습니다.',
    memo: '추가 비중 확대는 보류',
    next_action: '비중 축소 조건 정의',
    captures: [{ id: 'aapl-note', label: '메모 캡처', image_url: '/vite.svg' }],
    overlap_details: [{ type: 'holding', label: '대형 기술주', matched_symbol: 'MSFT', impact: 'high', reason: '기존 보유와 성격이 유사합니다.' }],
  },
}
