"""Minimal constants for signal engine v1."""

CODE_CASH = 0
CODE_HALF = 1
CODE_FULL = 2
CODE_REDUCE_1 = 3
CODE_REDUCE_2 = 4
CODE_REDUCE_3 = 5

OVERHEAT_NONE = 0
OVERHEAT_STAGE_1 = 1
OVERHEAT_STAGE_2 = 2
OVERHEAT_STAGE_3 = 3
OVERHEAT_STAGE_4 = 4
